name: CI/CD for Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/apiserver:${{ github.sha }} .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/apiserver:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/apiserver:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/apiserver:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/apiserver:latest
